name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # Replace 'main' with your branch name if different

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # You can choose a different runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags:heebow/SaveRestrictedContentBot:latest  # Replace with your details
